### ISSUE TITLE
Get a custom theme of pace instead of current minimal one

### ISSUE THREAD

**Issue by sakshamsaxena** [Frudor/Frudor#1]
Page loading needs to be considered eventually. Most probably will use AMD through RequireJS.

**Comment by faizanayubi** [comment]
Dont worry about page load we will use CDN to load external assets and caching for templates
the template engine in framework already cache the html page generated so it will run fast when hosted.
See https://github.com/SwiftMVC/SwiftMVC/wiki/Caching

The Page load time will be less than 3 sec in average 2G net speed india

**Comment by faizanayubi** [comment]
After 2GB bandwidth we will shift the platform on MEAN Stack...
